spring.application.name=sabanci_pharmacy

spring.datasource.url=jdbc:mysql://localhost:3306/db_308
spring.datasource.username=root
spring.datasource.password=samsepi0l
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.docker.compose.enabled=false